### ISSUE TITLE
fatal error when trying to open a shared folder containing `-` Or white space

### ISSUE THREAD

**Issue by tintamarre** [m0ppers/syncthing-bar#17]
I get a fatal error when i am trying to open a shared folder containing `-` or a white space (mine is named AGILO SC-SPRL) from the status bar.

**Comment by m0ppers** [comment]
wow...the open function was implemented in a way which is shameful even though i am a swift n00b. sorry. I don't want to release a bugfix release right away as there was a new release just today which had absolutely nothing to do with this bug here. So a secret release here:

http://mop.koeln/dump/syncthing-bar-0.0.7-pl1.pkg

**Comment by tintamarre** [comment]
thx.
