### ISSUE TITLE
show app title (UX improvement)

### ISSUE THREAD

**Issue by luebbert42** [m0ppers/syncthing-bar#3]
I have lots of icons in my top menu and need some reminder which was for what. Dropbox has this shiny little title bar as shown in the next screenshot. Idea?
![screenshot_06](https://cloud.githubusercontent.com/assets/422440/5684455/dabc40f6-9830-11e4-8080-35cb74cc9ddf.jpg)

**Comment by m0ppers** [comment]
hmm i consider the icon self explanatory. the less ui clutter the better. I don't have that many icons but Adium and the standard baritems don't have a separate headline and skype has some "Skype Wifi" which is probably just there due to marketing purposes :S 

closing this one unless there are more people forgetting about the logo ;)
