### ISSUE TITLE
Included syncthing binary seems to be unable to update

### ISSUE THREAD

**Issue by Alexander-Serov** [m0ppers/syncthing-bar#31]
This causes cross-platform cross-version compatibility issues. Terminal log:

> My-MacBook:syncthing user$ ./syncthing -version
> syncthing v0.14.6 "Dysprosium Dragonfly" (go1.7 darwin-amd64) jenkins@build.syncthing.net 2016-09-04 21:06:30 UTC
> My-MacBook:syncthing user$ ./syncthing -upgrade-check
> 15:55:21 FATAL: Upgrade: couldn't find a release to download

It shows a 2016 version, while the current version is that of June 2019. I have the latest version of `syncthing-bar` installed with `Homebrew`.

**Comment by m0ppers** [comment]
this project is obsolete now because there is an official thing:

https://github.com/syncthing/syncthing-macos

If you really want to use syncthing-bar you can easily replace the binary yourself inside the folder. from there things should just work (I am still using it because it just works - also upgrading seems to work). this seems to be only an issue for new installations. I will ask the homebrew people to remove it from their repos.

**Comment by Alexander-Serov** [comment]
Thank you for your answer. Indeed, removing the app from Homebrew would be the easiest way to avoid confusion.
